### ISSUE TITLE
Consider a back/refresh option

### ISSUE THREAD

**Issue by johngruen** [mozilla/tab-split-2#11]

**Comment by ianb** [comment]
I'm not sure what "back" means specifically, since there's not many ways to get the page to navigate. (Probably if the page triggers its own navigation it would work, like `location.href = newLocation`, but most navigation is suppressed). We could keep track of URLs visited though, and then "back" would mean "go to the previous page that was visited in the sidebar".

**Comment by ianb** [comment]
I think #55 fixes this, but the reload doesn't feel very satisfying. We might want to confirm that it really reloads the way we'd intend, it's not quite like the real reload button.
