### ISSUE TITLE
Include the addon linter

### ISSUE THREAD

**Issue by ianb** [mozilla/tab-split-2#38]
There's an example in Screenshots: https://github.com/mozilla-services/screenshots/blob/master/package.json#L91

**Comment by pdehaan** [comment]
I was going to submit a PR for this, but it seems non-trivial since the web-ext-artifacts/* directory can contain any number of ZIP files with archived add-ons. Also hitting issues with the ./package.json `version` number being out of sync w/ the ./addon/manifest.json version, so I can't use package.json variables to try and determine the latest/current version either.

I'll have to sort through the screenshots solution, but for some Shield stuff, I vaguely recall them creating a static symlink to the latest version so `linked-addon.xpi` always points to the most recent version: https://github.com/biancadanforth/tracking-protection-shield-study/blob/660336f87f359f622340a286c8c1ff1b8e0166df/bin/xpi.sh#L38-L41

**Comment by fzzzy** [comment]
@pdehaan ok, you win, i'll nuke the web-ext-artifacts dir :)

**Comment by fzzzy** [comment]
I opened https://github.com/mozilla/tab-split-2/issues/48 to automate keeping the package.json and manifest.json version numbers in sync.
