### ISSUE TITLE
Warn about CSP-blocked pages

### ISSUE THREAD

**Issue by ianb** [mozilla/tab-split-2#42]
Per #33, some pages won't work in iframes. We can still detect this, in the same code that we use to fix X-Frame-Options.

I propose:

- We detect X-Frame-Options
- We send a message with the URL affected to the sidebar when we see this
- The sidebar additionally checks that the URL being loaded is the affected URL, and in that case it removes the iframe and replaces it with a warning message (or maybe redirects the iframe to a warning page). This additional check is because the code that reads the header *might* catch requests that aren't coming from the sidebar.

Note [Bug 1318532](https://bugzilla.mozilla.org/show_bug.cgi?id=1318532) would fix this for us (by allowing us to use `<iframe mozbrowser>`), so it's not necessarily a permanent flaw in our approach (but it can't be fixed for launch).

**Comment by dveditz** [comment]
The intent of our CSP code is to play nice with extensions. For example the various -src directives are ignored if the content being loaded is a moz-extension: url and those are allowed to be loaded anyway when injected by an extension (Inline script still won't work because we can't tell that it was injected by an extension vs. an attack). We probably simply didn't add these checks to frame-ancestors and X-Frame-Options, which are checked in quite a different place from the resource-loading checks. Please file a bugzilla bug against "DOM: Security" to make this work.

Yes, this would mean a malicious extension can pull off the clickjacking attacks these features prevent, but a malicious extension is already bad news.

**Comment by ianb** [comment]
I take it back! It was all testpilot.firefox.com's fault, I shouldn't have used it for testing. https://github.com also uses that header, and the CSP mitigation does work! Probably this is because of testpilot.firefox.com's blacklist status.

I'll close this and instead do #33.
